version: '3.8'

services:
  quiclink:
    image: ghcr.io/suir1/quiclink:latest
    container_name: quiclink-server
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - ./src/server/config.json:/app/config.json
      - ./uploads:/app/uploads
    environment:
      - TZ=Asia/Shanghai
