version: '3.8'

services:
  quiclink:
    image: ghcr.io/suir1/quiclink:latest
    container_name: quiclink-server
    restart: unless-stopped
    ports:
      # - "3100:3100" # Optional: You can remove this if using 443
      - "443:3100"
      - "80:3101" # HTTP -> HTTPS Redirect
    volumes:
      - ./src/server/config.json:/app/config.json
      - ./uploads:/app/uploads
      # Mount SSL certificates (optional, required if using HTTPS)
      - ./cert.pem:/app/cert.pem
      - ./key.pem:/app/key.pem
    environment:
      - TZ=Asia/Shanghai
