// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function ConnectP2P(arg1, arg2) {
  return window['go']['main']['App']['ConnectP2P'](arg1, arg2);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DisconnectP2P() {
  return window['go']['main']['App']['DisconnectP2P']();
}

export function GetClipboard() {
  return window['go']['main']['App']['GetClipboard']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetDownloadDir() {
  return window['go']['main']['App']['GetDownloadDir']();
}

export function GetLocalServerPort() {
  return window['go']['main']['App']['GetLocalServerPort']();
}

export function GetP2PStatus() {
  return window['go']['main']['App']['GetP2PStatus']();
}

export function GetTransportMode() {
  return window['go']['main']['App']['GetTransportMode']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenDownloadDir() {
  return window['go']['main']['App']['OpenDownloadDir']();
}

export function SelectDownloadDir() {
  return window['go']['main']['App']['SelectDownloadDir']();
}

export function SendClipboard() {
  return window['go']['main']['App']['SendClipboard']();
}

export function SendGenericMessage(arg1, arg2) {
  return window['go']['main']['App']['SendGenericMessage'](arg1, arg2);
}

export function SendP2PHello() {
  return window['go']['main']['App']['SendP2PHello']();
}

export function SetClipboard(arg1) {
  return window['go']['main']['App']['SetClipboard'](arg1);
}

export function ShareFileP2P(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ShareFileP2P'](arg1, arg2, arg3, arg4);
}
