// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ConnectP2P(arg1:string,arg2:string):Promise<void>;

export function Disconnect():Promise<void>;

export function DisconnectP2P():Promise<void>;

export function GetClipboard():Promise<string>;

export function GetConnectionStatus():Promise<boolean>;

export function GetP2PStatus():Promise<boolean>;

export function Greet(arg1:string):Promise<string>;

export function SendClipboard():Promise<void>;

export function SendGenericMessage(arg1:string,arg2:Record<string, any>):Promise<void>;

export function SendP2PHello():Promise<void>;

export function SetClipboard(arg1:string):Promise<void>;

export function ShareFileP2P(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;
